/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2019-01-03 03:07:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>注册界面</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function CheckTel(){\r\n");
      out.write("   if(document.form2.TextTel.value==\"\"){\r\n");
      out.write("   document.getElementById(\"king2\").innerHTML=\"手机号不能为空！\";\r\n");
      out.write("   return false;\r\n");
      out.write("     }\r\n");
      out.write("var phone= document.form2.TextTel.value;\r\n");
      out.write("  var a=/^1[3,4,5,7,8]\\d{9}$/;\r\n");
      out.write("  var b=a.test(phone);\r\n");
      out.write("  if(b){\r\n");
      out.write("document.getElementById(\"king2\").innerHTML=\"\";\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("else{\r\n");
      out.write("    document.getElementById(\"king2\").innerHTML=\"手机号格式错误\";\r\n");
      out.write("     return false;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("function CheckEmail(){\r\n");
      out.write("    if(document.form2.TextEmail.value==\"\"){\r\n");
      out.write("          document.getElementById(\"king3\").innerHTML=\"邮箱不能为空!\";\r\n");
      out.write("          return false;\r\n");
      out.write("          }\r\n");
      out.write("    var Email=document.form2.TextEmail.value;\r\n");
      out.write("       var a1=/\\w{1,}@\\w+\\.\\w{2,3}/\r\n");
      out.write("       var b1=a1.test(Email);\r\n");
      out.write("       if(b1){\r\n");
      out.write("          document.getElementById(\"king3\").innerHTML=\"\";\r\n");
      out.write("          return true;\r\n");
      out.write("          }\r\n");
      out.write("          else{\r\n");
      out.write("          document.getElementById(\"king3\").innerHTML=\"邮箱格式错误!\";\r\n");
      out.write("           return false;\r\n");
      out.write("             }\r\n");
      out.write("}\r\n");
      out.write("function CheckPwd(){\r\n");
      out.write("   var pwd=document.form2.TextPwd.value;\r\n");
      out.write("   if(pwd==\"\"){\r\n");
      out.write("   document.getElementById(\"king1\").innerHTML=\"密码不能为空！\";\r\n");
      out.write("     return false;\r\n");
      out.write("   }\r\n");
      out.write("   if(pwd.length<6){\r\n");
      out.write("      document.getElementById(\"king1\").innerHTML=\"密码长度不够\";\r\n");
      out.write("         return false;\r\n");
      out.write("      \r\n");
      out.write("   }\r\n");
      out.write("   document.getElementById(\"king1\").innerHTML=\"\";\r\n");
      out.write("     return true;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("function CheckSubmit(){\r\n");
      out.write("    return  CheckTel()&&CheckPwd()&&CheckEmail();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<div>\r\n");
      out.write("<center>\r\n");
      out.write("</div>\r\n");
      out.write("<body background=i/123.jpg>\r\n");
      out.write("<div id =  \"last\" style=\" width:100%;float:left\" >\r\n");
      out.write("  <h1 style=\"font-size:30px; text-align:left\" >注册新用户 <span style=\"font-size:20px\">完成手机/邮箱验证注册，可以获得礼品券哦！</span></h1>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write(" </div> \r\n");
      out.write("<form id=\"form1\" name=\"form2\" method=\"post\" action=\"registerHandler.jsp\" onsubmit=\"return CheckSubmit()\">\r\n");
      out.write("  <table >\r\n");
      out.write("  <tr>\r\n");
      out.write("      <td >用户名:</td>\r\n");
      out.write("      <td >\r\n");
      out.write("      <input type=\"text\" name=\"username\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>密码:</td>\r\n");
      out.write("      <td >\r\n");
      out.write("      <input name=\"password\" type=\"password\" id=\"TextPwd\" onblur=\"CheckPwd()\"/>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td><span id=\"king1\">&nbsp;</span></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td >手机号:</td>\r\n");
      out.write("      <td >\r\n");
      out.write("      <input name=\"tel\" type=\"text\" id=\"TextTel\"onblur=\"CheckTel()\" />\r\n");
      out.write("      </td>\r\n");
      out.write("      <td ><span id=\"king2\">&nbsp;</span></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td >邮箱:</td>\r\n");
      out.write("      <td >\r\n");
      out.write("      <input name=\"email\" type=\"text\" id=\"TextEmail\"onblur=\"CheckEmail()\" />\r\n");
      out.write("      </td>\r\n");
      out.write("      <td ><span id=\"king3\">&nbsp;</span></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("   <input type=\"submit\"  value=\"立即注册\">\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
